services:
  ebpf-monitor:
    build: .
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - /sys/kernel/btf:/sys/kernel/btf:ro
      - /sys/fs/bpf:/sys/fs/bpf
      - /lib/x86_64-linux-gnu/libssl.so.3:/lib/x86_64-linux-gnu/libssl.so.3:ro
    command:
      - "-lib=/lib/x86_64-linux-gnu/libssl.so.3"
      - "-metrics=:9091"
      - "-loki=http://127.0.0.1:3100/loki/api/v1/push"
      - "-exclude=monitor,loki,prometheus,grafana,lifecycle-serve"
    restart: always
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus
      - loki